### ISSUE TITLE
Case where ObjectBuilder is not typesafe

### ISSUE THREAD

**Issue by adinvadim** [anton-kravchenko/ObjectBuilder#25]
Hi!
Thank you for your arcticle and repo

Case where Object Builder is not typesafe (in this case typescript doesnt throw error):

```typescript

type From = { id?: string };
type To = { id: string };

const mapper = (a: From): To => {
  return ObjectBuilder.new<To>()
    .with('id', a.id)
    .build();
};

mapper({}).id.toLowerCase()
```

**Comment by adinvadim** [comment]
My bad. I don't have strict: true in tsconfig.json

**Comment by anton-kravchenko** [comment]
No worries! Thank you for taking your time to read the article and check
out the repo!
